[package]
name = "alphacoders-dl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.6"
ureq = "2.2.0"
regex = "1.5.4"
select = "0.5.0"
anyhow = "1.0"